<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="user_story_09_user_story_08" nsURI="http://cdapackage/user_story_09/user_story_08/DeleteConflictReason"
    nsPrefix="CDAPackage">
  <eClassifiers xsi:type="ecore:EClass" name="#|5|_|15|:Secondary Entity#">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;information&quot;->  _ &quot;information&quot;"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
