<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_37_user_story_36" nsURI="http://cdapackage/user_story_37/user_story_36/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|3|_|12|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/1/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/1/%23|13|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/3/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/4/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/4/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/5/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/6/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/7/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/8/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/11/%23|13|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/12/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/12/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/13/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/16/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/17/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/17/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/18/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/20/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/21/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/24/%23|13|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/24/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/25/%23|13|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/26/%23|15|_|7|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/27/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_36_user_story_37" nsURI="http://cdapackage/user_story_36/user_story_37/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/28/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/28/|16|_|8|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|8|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
