<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_19_user_story_14" nsURI="http://cdapackage/user_story_19/user_story_14/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|7|_|18|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;issue&quot;->  _ &quot;issue&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_14_user_story_19" nsURI="http://cdapackage/user_story_14/user_story_19/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|18|_|7|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;issue&quot;->  _ &quot;issue&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
