<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_24_user_story_10" nsURI="http://cdapackage/user_story_24/user_story_10/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|19|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Perform&quot; _ &quot;Perform&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/0/|3|_|16|%3APrimary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|0|_|13|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff member&quot; _ &quot;Staff member&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/0/%23|11|_|19|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|3|_|16|:Primary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff Review&quot; _ &quot;Completeness Review&quot;->&quot;Completeness Review&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|1|_|14|:Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#primary actions#" eType="#/0/%23|11|_|19|%3APrimary%20Action%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_24" nsURI="http://cdapackage/user_story_10/user_story_24/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|19|_|11|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Perform&quot; _ &quot;Perform&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/1/|16|_|3|%3APrimary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|3|:Primary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Completeness Review&quot; _ &quot;Staff Review&quot;->&quot;Staff Review&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|14|_|1|:Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#primary actions#" eType="#/1/%23|19|_|11|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|13|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff member&quot; _ &quot;Staff member&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/1/%23|19|_|11|%3APrimary%20Action%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
