<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_16_user_story_21" nsURI="http://cdapackage/user_story_16/user_story_21/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|2|_|10|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;track&quot;->  _ &quot;track&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_21_user_story_16" nsURI="http://cdapackage/user_story_21/user_story_16/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;track&quot;->  _ &quot;track&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
