<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_52_user_story_01" nsURI="http://cdapackage/user_story_52/user_story_01/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|3|_|11|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;obtain&quot;->  _ &quot;obtain&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|2|_|10|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;search&quot;->  _ &quot;search&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_01_user_story_52" nsURI="http://cdapackage/user_story_01/user_story_52/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;search&quot;->  _ &quot;search&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;obtain&quot;->  _ &quot;obtain&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_01_user_story_52" nsURI="http://cdapackage/user_story_01/user_story_52/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;search&quot;->  _ &quot;search&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_01_user_story_52" nsURI="http://cdapackage/user_story_01/user_story_52/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;obtain&quot;->  _ &quot;obtain&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
