<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_29_user_story_12" nsURI="http://cdapackage/user_story_29/user_story_12/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|8|_|16|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Assign&quot; _ &quot;Assign&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/0/|3|_|13|%3APrimary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|0|_|10|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff member&quot; _ &quot;Staff member&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/0/%23|8|_|16|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|1|_|11|:Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#primary actions#" eType="#/0/%23|8|_|16|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|3|_|13|:Primary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Hearing Date&quot; _ &quot;Application&quot;->&quot;Application&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_12_user_story_29" nsURI="http://cdapackage/user_story_12/user_story_29/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|16|_|8|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Assign&quot; _ &quot;Assign&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/1/|13|_|3|%3APrimary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|11|_|1|:Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#primary actions#" eType="#/1/%23|16|_|8|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|10|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff member&quot; _ &quot;Staff member&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/1/%23|16|_|8|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|13|_|3|:Primary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Application&quot; _ &quot;Hearing Date&quot;->&quot;Hearing Date&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
