<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_18_user_story_17" nsURI="http://cdapackage/user_story_18/user_story_17/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|6|_|15|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Manage&quot; _ &quot;Manage&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/0/|3|_|11|%3APrimary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|3|_|11|:Primary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Ordinances&quot; _ &quot;Approved Proffers&quot;->&quot;Approved Proffers&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|0|_|8|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff member&quot; _ &quot;Staff member&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/0/%23|6|_|15|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|1|_|9|:Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#primary actions#" eType="#/0/%23|6|_|15|%3APrimary%20Action%23"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_17_user_story_18" nsURI="http://cdapackage/user_story_17/user_story_18/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Manage&quot; _ &quot;Manage&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/1/|11|_|3|%3APrimary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Staff member&quot; _ &quot;Staff member&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/1/%23|15|_|6|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|11|_|3|:Primary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;Approved Proffers&quot; _ &quot;Ordinances&quot;->&quot;Ordinances&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|1|:Action">
      <eStructuralFeatures xsi:type="ecore:EReference" name="#primary actions#" eType="#/1/%23|15|_|6|%3APrimary%20Action%23"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
