<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_09_user_story_10" nsURI="http://cdapackage/user_story_09/user_story_10/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|5|_|14|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|0|_|9|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/0/%23|2|_|11|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/0/%23|3|_|12|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|2|_|11|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|3|_|12|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/1/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/3/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/4/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/4/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/5/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/5/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/6/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/7/%23|11|_|2|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/7/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/8/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/9/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/10/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/10/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/13/%23|11|_|2|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/13/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/16/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/17/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/19/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/20/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/21/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/22/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/22/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/23/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/24/%23|11|_|2|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/24/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/24/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/25/%23|11|_|2|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/25/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/26/%23|11|_|2|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/26/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/27/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/27/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/28/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/29/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/31/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/32/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/32/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/33/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/34/%23|11|_|2|%3APrimary%20Action%23"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/34/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/34/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/35/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/35/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/37/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/38/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/39/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/40/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/43/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/44/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/46/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/48/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/50/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/51/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/52/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/52/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/53/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/53/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/54/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|13|_|4|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;&quot;->  _ &quot;&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/54/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;experiment&quot; _ &quot;experiment&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/56/%23|14|_|5|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/57/%23|11|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;create&quot;->  _ &quot;create&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_10_user_story_09" nsURI="http://cdapackage/user_story_10/user_story_09/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|5|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;log book page&quot;->  _ &quot;log book page&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|9|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;researcher&quot; _ &quot;researcher&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/58/%23|12|_|3|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|3|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;attach&quot;->  _ &quot;attach&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
