<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_34_user_story_35" nsURI="http://cdapackage/user_story_34/user_story_35/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|4|_|12|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/1/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/2/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/2/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/7/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/8/%23|14|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/9/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/10/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/11/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/12/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/13/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/14/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/15/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/16/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/17/%23|14|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/18/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/18/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/19/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/20/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/20/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/21/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/21/%23|14|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/23/%23|14|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/23/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/25/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|14|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/27/|15|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|15|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/27/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_35_user_story_34" nsURI="http://cdapackage/user_story_35/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
