<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore">
  <ecore:EPackage name="user_story_34_user_story_37" nsURI="http://cdapackage/user_story_34/user_story_37/SymmetricReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|6|_|15|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/1/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/2/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/3/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/4/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/5/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/6/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/7/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/8/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/11/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/12/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/13/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/13/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/14/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/15/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/15/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/16/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/17/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/17/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/18/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/18/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/20/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/20/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/21/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/22/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/27/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/28/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/29/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/30/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/30/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/31/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/31/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/32/%23|12|_|4|%3APrimary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#targets#" eType="#/32/%23|15|_|6|%3ASecondary%20Entity%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/33/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="#|12|_|4|:Primary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;measures&quot;->  _ &quot;measures&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
  <ecore:EPackage name="user_story_37_user_story_34" nsURI="http://cdapackage/user_story_37/user_story_34/DeleteConflictReason"
      nsPrefix="CDAPackage">
    <eClassifiers xsi:type="ecore:EClass" name="|8|_|0|:Persona">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;api user&quot; _ &quot;api user&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#triggers#" eType="#/35/%23|10|_|2|%3APrimary%20Action%23"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|10|_|2|:Primary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;normalise&quot;->  _ &quot;normalise&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|15|_|6|:Secondary Entity#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;datasets&quot;->  _ &quot;datasets&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="#contains#" eType="#/35/|16|_|7|%3ASecondary%20Entity"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="|16|_|7|:Secondary Entity">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;contextual constraints&quot; _ &quot;contextual constraints&quot;"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="#|11|_|3|:Secondary Action#">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="name=&quot;work&quot;->  _ &quot;work&quot;-> "
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
  </ecore:EPackage>
</xmi:XMI>
